### ISSUE TITLE
[TASK] TLVF: Add TLVF support for dynamic list of classes

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#115]
## Description

Currently the TLV factory only has support for variable length lists of none simple types (classes) if the internal list type is a class which also has a variable length list.
This enforces the YAMLs which have such lists to be less readable, since these have to be defined in the TLV class itself instead of different class.

Example TLV class which lacks the support:
```yaml
cOuter:
  _type: class
  list_length:
    _type: uint16_t
    _length_var: True
  list:
    _type: cInner
    _length: [ list_length ]
  var1: uint32_t

cInner:
  _type: class
  var1: uint32_t
  var2: uint16_t
```
In this example, the tlvf.py script will not generate the `memmov` and the updating of `cOuter`s `var1` on list allocation.

## Exit criteria

- Add support for the above example
- Update `tlvWscM1.yaml` and `tlvWscM2.yaml` files so that all variable length members will be defined in the `WSC_attributes.yaml` file as the rest of the members.
- Pass DoD - `./tools/docker/tests/test_gw_repeater.sh --rm` with `Wireshark` open and see that the correct values are set in the M1 and M2 TLVs.
