### ISSUE TITLE
[TASK] TLVF: forcing allocation order in multiple lists classes

### ISSUE THREAD

**Issue by LiorAmram** [prplfoundation/prplMesh#116]
## Description
Following this [task](https://github.com/prplfoundation/prplMesh/issues/115), there is a gap in tlvf in a case there is a simple list followed by a nested list.
for example:

```
tlvSample:
    _type: class
    _is_tlv_class: true
    type: eTlvType
    length: uint16_t

    simple_list_length:
        _type: uint16_t
        _length_var: true
    simple_list:
        _type: uint16_t
        _length: [simple_list_length]

    complex_list_length:
        _type: uint16_t
        _length_var: true
    complex_list:
        _type: cInner
        _length: [complex_list_length]

cInner:
    _type: class
    inner_list_length:
        _type: uint16_t
        _length_var: true
    inner_list:
        _type: uint16_t
        _length: [inner_list_length]
    inner_param: uint32_t
```

In this case, allocation of simple list won't be aware of the the `inner_param` (notice there are multiple instances of it, because complex_list can contain multiple entries), and therefore won't update its pointer, which will cause data corruption.

## Possible solutions
Updating all the following pointers is very complex, and may result in a very complex generated code.
My suggestion is 'locking' the allocation, forcing the user to allocate lists' entries by order.
Each class will have a integer lock_order_counter which will be initialized to 0.
Each list/inner class will have its own list_index (internally, can be managed in python, and generated as hard coded 'magic numbers' in the c++ code. Doesn't require additional variables).
When calling alloc/create - the method will check the lock_order_counter:
if `lock_order_counter > list_index` - return false.
if `lock_order_counter <= list_index` - set `lock_order_counter = list_index` and continue.

That way, the user will be forced to to work on the lists in order, and we can avoid corrupted data.
