### ISSUE TITLE
[BUG] TLVF: empty class member initialization 

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#480]
**Describe the bug** -
The following tlv class is used by tlvf_test to verify various TLVF functionalities:
```yaml
 _type: class
  _is_tlv_class : True
  # TODO tlvf currently requires type to be first field
  type:
    _type: uint8_t
    _value_const: 99
  # TODO tlvf currently requires length to be second field
  length: uint16_t
  var0: uint16_t

  # TODO tlvf currently doesn't support list length field of more than 1 byte
  simple_list_length: uint8_t
  simple_list:
    _type: uint16_t
    _length: [ simple_list_length ]
  
  test_string_length: uint8_t
  test_string:
    _type: char
    _length: [ test_string_length ]
    _length_max: 8

  # TODO tlvf currently doesn't support list length field of more than 1 byte
  complex_list_length: uint8_t
  complex_list:
    _type: cInner
    _length: [ complex_list_length ]

  var1: cInner
  var2: uint32_t
  unknown_length_list:
    _type: cInner
    _length: []

cInner:
  _type: class
  _is_tlv_class: true
  type:
    _type: uint16_t
    _value_const: 1
  # TODO tlvf currently requires length to be second field
  length: uint16_t
  # TODO tlvf currently doesn't support list length field of more than 1 byte
  list_length: uint8_t
  list:
    _type: uint8_t
    _length: [ list_length ]
  var1: uint32_t
  unknown_length_list_inner:
    _type: char
    _length: []

```

Since `var1` is a class member, it might contain variable-length / unknown-length lists. For this reason, its `init()` function doesn't create `var1` when it is first created in a `CmduMessageTx` (`parse == false`).
However, when `tlvVarlist` is created in a `CmduMessageRx` (`parse == true`), `var1` is created automatically by the `init()` function since its length is already known and cannot change.

This leads to the following confusing code when the user just wants to send the default values - `var1` still has to be added manually:

```
auto tlv4 = msg.addClass<tlvTestVarList>();
tlv4->add_var1(tlv4->create_var1());
msg.finalize(true);
```

This is not very intuitive and leads to cases where the user simply does not add `var1` which causes various and very hard to find errors.

A better outcome should be that `finalize()` will fail if such variables are present in one of the TLVs and were not added.

## Steps to reproduce

1. Remove the initialization of `var1` in tlvf_test.cpp: test_parser() function
2. Build
3. Run tlvf_test

## Expected behavior

Finalize will fail with a clear error message if any TLV inside the CMDU is not fully initialized.
